### ISSUE TITLE
W&G not compatible ? [BUG]

### ISSUE THREAD

**Issue by Dark-Elyrion** [League-of-Foundry-Developers/fvtt-module-trigger-happy#102]
**Module Version:** v0.8.39

**Describe the bug**
I'm following the instruction on that video :https://www.youtube.com/watch?v=Id9AVvSxonI&ab_channel=JorgePongitor
and it seems that when I arrive à the simple step [36:26 in the video] of creating a character, creating the journal entry and clicking the actor with the line of code added in the journal entry : it does nothing. No message bug, no internal error. Nada ! I have even cut all other modules that I used normally to have only the 3 that he use (and lib wrapper because FX master doesn't work without).

Is it because I'm using the Wrath & Glory Setup that it wont work ?

**Foundry Version:** 9 build 269 table

**Game System:**  Windows 10

**Additional context**
Add any other context (like other modules installed) about the problem here.

**Comment by p4535992** [comment]
@Dark-Elyrion sorry Trigger is happy is not followed anymore it's advisable to use MATT (Monk Actvie Tile Trigger) instead

**Comment by Dark-Elyrion** [comment]
Thank you for the advise.

Will do and great continuation !
