### ISSUE TITLE
[BUG] Support for fvtt10

### ISSUE THREAD

**Issue by Rubengam3r** [League-of-Foundry-Developers/fvtt-module-trigger-happy#104]
**Module Version:** v0.8.12

**Before open any issue**

1) Enable the module setting _"Enable debugging"_
2) Click F12 go to the _console_ tab 
3) make the test you want and replicate the error
4) Go to the tab console open on point 2) and just right click and click 'Save as' and 'Save' or send a screenshot of the exception on the console.
5) Attach the text file on the github issue with all the logs related tot he module, or send a screenshot of the messages on the console.

**Describe the bug**
I tried to install the module using the manifest URL  and was given the Error unable to load valid module maifest data

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem
![unknown_2022 09 03-16 44](https://user-images.githubusercontent.com/32652791/188289829-be111606-508b-4304-846a-fd2c15b5f24f.png)
m.

**Browser:**
 - 

**Foundry Version:** 
Version 10 build 284
**Game System:** 

**Additional context**
Add any other context (like other modules installed) about the problem here.

**Comment by p4535992** [comment]
Sorry @Rubengam3r it has been a long time since this module was abandoned in favor of [MATT](https://foundryvtt.com/packages/monks-active-tiles) (read the README FILE). Unfortunately I cannot compete with Ironmonk on XD interfaces.
