### ISSUE TITLE
Compability warning during startup [BUG]

### ISSUE THREAD

**Issue by Mathias2803** [League-of-Foundry-Developers/fvtt-module-trigger-happy#106]
**Module Version:** v0.10.01

**Describe the bug**
There is a warning message after startup from this module.

**To Reproduce**
Just restart Foundry.

**Screenshots**
setup.js:145
[trigger-happy] The module "trigger-happy" contains compendium pack data which uses the deprecated "entity" field which must be migrated to "type"

**Browser:**
Google Chrome

**Foundry Version:** 
Version 10 - Build 288

**Game System:** 
DnD5e 2.0.3

**Comment by p4535992** [comment]
Trigger happy is abbandoned in favor of MATT

**Comment by tposney** [comment]
I'll update the v10 release to fix the compatibility warning. But as mentioned the module is not being developed any further.
