### ISSUE TITLE
Doorstate triggers don't behave as expected.

### ISSUE THREAD

**Issue by Mavendorn** [League-of-Foundry-Developers/fvtt-module-trigger-happy#18]
When using the trigger option doorClose, if the door in question is originally in a locked state when the GM unlocks the door the doorstate changes back to closed. Triggerhappy then executes the effects due to the state change to closed but intuitively it should've ignored the state change from locked to close (as the door is closed in both states) and only execute the effects when the door changes state from open to closed.
Can you make this the default behavior for the trigger option or provide an option to do so?

**Comment by tposney** [comment]
Hmm. I'll push a fix for this in 0.8.7
