### ISSUE TITLE
Possibility to escape bracket ("]") characters for messages inside @ChatMessages

### ISSUE THREAD

**Issue by Voidchimera** [League-of-Foundry-Developers/fvtt-module-trigger-happy#22]
Hello, I wanted to ask if there's a way to escape brackets inside @ChatMessages's text content. I ask because the system module for GURPS, has "On the Fly" formulas that create a button in the chat window by writing the adequate formula between brackets. An example could be [DX], [ST-1], [S:name-2 text], etc. 
More formulas can be found in their read me: https://docs.google.com/document/d/1NMBPt9KhA9aGG1_kZxyk8ncuOKhz9Z6o7vPS8JcjdWc/edit#heading=h.4i42gorf4hic

The issue I've been running into is when I use the brackets for these OtF commands, here's an example:
`@Actor[JG5kjzSWeT4gnSDV]{Trap 1}@Trigger[move capture]@ChatMessage[You have triggered a trap]@ChatMessage["Roll against [DX]. See what happens."]`

This outputs the following when the trigger is triggered:
![image](https://user-images.githubusercontent.com/77585598/110255362-0877cb80-7f72-11eb-83e1-7b752e1cfa83.png)

The issue happens with the "]" bracket and it ends the message there, but not completing the OtF command that I  need. I think that this can be solved if you can escape that bracket somehow, but after trying a few alternatives I can't find a way to do it.

That's it, thank you guys.

**Comment by kakaroto** [comment]
I'd say the easy solution for that would be to simply use `@Macro[roll-against-dx]` and have a Chat macro with all the text you want. and anything you might want to put in there.
