### ISSUE TITLE
just installed this to use on my CP Red game is not working

### ISSUE THREAD

**Issue by Hyriu33** [League-of-Foundry-Developers/fvtt-module-trigger-happy#23]
Tried to follow both the video and your tutorial

I can't seem to make it work. 

Tried this way it didnt work 
![image](https://user-images.githubusercontent.com/80231419/110264288-02401a00-7f87-11eb-9f06-86677af9e4f1.png)

Tried this way it didnt work either
![image](https://user-images.githubusercontent.com/80231419/110264430-47644c00-7f87-11eb-97ab-7164ac0be36f.png)

![image](https://user-images.githubusercontent.com/80231419/110264165-a1184680-7f86-11eb-8912-96821ad5a0db.png)

![image](https://user-images.githubusercontent.com/80231419/110264182-ae353580-7f86-11eb-93c3-ac9e9300f75f.png)

Any help will be appreciated. 

Thanks

**Comment by tposney** [comment]
Apologies for the delay in getting back to you. What were you trying to accomplish?

**Comment by tposney** [comment]
What you have looks right. I assume you attempted to trigger by clicking on the token on the map? Make sure that the special enable button is ticked, (the happy face in the attached screenshot).
![Screenshot from 2021-05-18 23-49-39](https://user-images.githubusercontent.com/4486143/118663001-ca313f00-b833-11eb-9c3e-347d888ea455.jpg)

The other thing to check that the token name/id text is pure text - examine the source by using the "<>" option and make sure there is nothing extra there.

**Comment by p4535992** [comment]
Still not working with version 0.8.21 ?
