### ISSUE TITLE
Issue with "Trigger[click]" in Pathfinder 2e system

### ISSUE THREAD

**Issue by djmove1981** [League-of-Foundry-Developers/fvtt-module-trigger-happy#24]
Was trying to make a landing page in Pathfinder 2e and was following the following guide ([Foundry Tips and Tricks – Let’s build a Landing Page!](https://www.foundryvtt-hub.com/showcase/foundry-tips-and-tricks-lets-build-a-landing-page/)) and could not get any "Trigger[click]" to function.

Tried many things, went through the Read Me, and tried using the Fake Note that comes with the module, but modifying it to react to a click and still didn't function.

Tried reproducing it in Pathfinder 1e, using the Fake Note again, and it worked like a charm.

**Comment by tposney** [comment]
I just tried the fake note trigger happy and it worked for me.
A couple of things to be careful of (pardon me if you know all this already):
@Token[Some Token] - requires the token name (token settings on the map) to be Some Token
The journal link needs to be created afresh in each world (as it references the journal ID).
If you can't get it working, ping me in discord (@tposney) and if possible I'll connect to your world to see what is going on.

**Comment by djmove1981** [comment]
I made several attempts since you replied and it still wasn’t working. So, I was going to record a video of every step I was performing, so you could see if I was doing anything wrong. And just to annoy me, it started working. Guess it’s the old trick it was pulling on me that it only goes wrong until you show somebody else.

Thanks for taking the time to reply and verify it on your side.

Joe
