### ISSUE TITLE
Support triggering from map notes

### ISSUE THREAD

**Issue by DemianWright** [League-of-Foundry-Developers/fvtt-module-trigger-happy#25]
Since [foundryvtt-multilevel-tokens](https://github.com/grandseiken/foundryvtt-multilevel-tokens) works on map notes and this module works on tokens, there's clearly a missed opportunity in not being able to use both of these modules using the same triggering method.

I propose a new `@Note[Text label]` trigger.

**Comment by p4535992** [comment]
From 0.8.12 now you can use the annotation @JournalEntry for trigger or use like a effect
