### ISSUE TITLE
Drawing with Trigger set to capture does not work

### ISSUE THREAD

**Issue by Beff42** [League-of-Foundry-Developers/fvtt-module-trigger-happy#28]
How to reproduce:
Drawing with label 'Trap', Journal entry 'You have triggered a trap' and the Trigger, resulting in the following Trigger Happy journal entry:
@Drawing[Trap] @Trigger[capture] @JournalEntry[You have triggered a trap]
![capture](https://user-images.githubusercontent.com/83531917/116806126-54d32800-ab2b-11eb-8578-a022fcf4e1b4.png)
When the actor moves in the trap (or drags the token above it), it will be ported/end its movement in the center of the drawing and the journal entry will not open. Same behaviour for trigger token of size 3x3 or bigger.

Expected behaviour:
Everything is working fine with move, trigger happy entry:
@Drawing[Trap] @Trigger[move] @JournalEntry[You have triggered a trap]
When the actor moves in the trap it will end its movement in the first entered grid square and the journal entry will show.

I would prefer to use the capture option though, since some of my players rather use the mouse, not the keyboard to navigate.

**Comment by tposney** [comment]
The code is working as intended, that is captured tokens are always moved to the centre of the trap token/drawing.
I think I still have some code that will do what you want (at least for tokens). I'll investigate

**Comment by Beff42** [comment]
Thanks for checking that out!
I see now, that the expected capture behaviour is not as straight forward as I thought at first. Since it might be hard to get the first grid square the movement collides with the Drawing/Token. And I also see it's mentioned in the readme ^^'

BTW the journal entry did not open for me either, but that was since the 'capture' Trigger has to be used together with the 'move' Trigger (the trap was not hidden for testing, so it was 'click' by default). I did not know, that some Triggers can only be used together, but that's resolved then.

Background to my question is, that I try to trigger a macro whenever my player cross a certain grid square. I want to automatic doors. But since some of them use iPads to play, they might just jump right over it and the macro would not be triggered 🤔

**Comment by tposney** [comment]
Couple of points. The capture trigger is "different" it simply stops the token movement. To trigger an action it needs to be coupled with move, so usually it would look like
```
@Token[Name]@Trigger[capture move]@ChatMessage[Token captuted]
```
As of version 0.8.3 there is an option to allow capturing at the edge of a token/drawing rather than the centre, although it treats drawings as rectangular which is not ideal. It requires foundry 0.8+ to work.
