### ISSUE TITLE
Triggers do not work with Edge Browser

### ISSUE THREAD

**Issue by Razortide** [League-of-Foundry-Developers/fvtt-module-trigger-happy#34]
Hey, I just found that MS Edge is not working with Trigger Happy anymore (it worked in the past).
I can open journal entries clicking on triggers just fine when using Chrome, but if I switch to Edge, it is not working anymore.

I am running Foundry 0.7.10, Trigger Happy 0.8.2, Edge 91.0.864.41 (64bit)

**Comment by tposney** [comment]
I'm not really in a position to continue doing fixes for the 0.7 branch of
foundry.  I did test it in foundry 0.8.6 and it seemed to work fine.
If you can have a look at the developer console and see if there are any
errors I might be able to fix it for 0.7.x foundry.

**Comment by Razortide** [comment]
If it is fine for 0.8.X and beyond, I guess I'll just wait :)

**Comment by tposney** [comment]
Well please make sure that it is ok in your case, but yes it seems to be
for me.

**Comment by Razortide** [comment]
Hey @tposney, I can confirm its working with 0.8.6.
Thank you!
