### ISSUE TITLE
@Chatmessage command not executing

### ISSUE THREAD

**Issue by jtgeraldes** [League-of-Foundry-Developers/fvtt-module-trigger-happy#35]
After updating to Foundry 0.8.6, the command @ChatMessage[/DoTrapAttack "XXX" "YYY" BBB] is printing on chat instead of calling the macro (@Trigger is working fine so far).

Versions:
Foundry v 0.8.6
DnD5e Ruleset v 1.3.3
Advanced Macros v 1.6
The Furnace v 2.6.0
Midi-QoL v0.8.10
TriggerHappy v0.8.6

Macro DoTrapAttack (set as script macro and Execute as GM): 
```
// Requires midi-qol to work at all
// Rolls an attack from actor args[0] using item args[1] and display a token args[2]
let tactor = game.actors.entities.find(a => a.name === args[0])
if (!tactor) return `/Whisper GM "DoTrap: Target token ${args[0]} not found"`
let item = tactor.items.find(i=>  i.name === args[1])
if (!item) return `/Whisper GM "DoTrap: Item ${args[1]} not found"`
let oldTargets = game.user.targets;
game.user.targets = new Set().add(token);
let trapToken = canvas.tokens.placeables.find(t=>t.name === args[2]);
new MidiQOL.TrapWorkflow(tactor, item, [token], trapToken.center)
game.cub.removeAllConditions(trapToken);
if (trapToken) await trapToken.update({"hidden" : false});
```

**Comment by trdischat** [comment]
With the update to FVTT 0.8.6, The Furnace is now EOL, and the advanced macros have moved to the new Advanced Macros module.  Unfortunately, this new module outputs the chat macros invocation to the Chat Log.  And with the latest update to version 1.6 of Advanced Macros, it no longer runs chat macros at all.  This is rather crippling for Trigger Happy.

**Comment by jtgeraldes** [comment]
Thanks for the update. 

Is there any turnaround for macro execution until we have a fix on Advanced Macros (if this is planned)?

**Comment by kakaroto** [comment]
Advanced macros was fixed yesterday to support `/command` support. See https://github.com/League-of-Foundry-Developers/fvtt-advanced-macros/issues/5

I expect there would be a release soon with the fix.

**Comment by jtgeraldes** [comment]
Just tested the update v 1.7 released yesterday and chat macros on Trigger Happy are now being called as expected. 

Thanks a million for the very quick fix. I've taken the liberty to close the issue.
