### ISSUE TITLE
Scene doesn't load tokens sometimes when changing scenes by @Trigger[cliclk]

### ISSUE THREAD

**Issue by igorteuri** [League-of-Foundry-Developers/fvtt-module-trigger-happy#37]
Foundry version, 8.6
System D&D 5e 1.3.3

I'm trying to create a interactive Menu on my Landing Page using trigger happy.
Sometimes, when I change the scene using @Trigger[click] the tokens doesn't load. 

I get these errors on console (image).
I've tested disabling all modules but Trigger Happy, the error persists. 
I've tried disabling all modules and switch scenes by the default interface of foundry, in this scenario the error doesn't occur.

![image](https://user-images.githubusercontent.com/64547748/121939603-927ac180-cd23-11eb-8194-a9f2af10cf8a.png)

**Comment by tposney** [comment]
I've made a change to this, please try version 0.8.7 and see if the problem goes away.
