### ISSUE TITLE
@Token[click] not working

### ISSUE THREAD

**Issue by YaruKo** [League-of-Foundry-Developers/fvtt-module-trigger-happy#38]
Hello 
I tried setting up chatters for my market place following Kobold DMs guide: https://www.youtube.com/watch?v=W6z0pMUBAz8& but for some reason the macro is not triggered when the token is clicked. I double checked every line, it's spelled correctly, the scene is active etc. The macro works when I manually click the macro it also targets the correct token but somehow the trigger is not working. Am I missing something obvious? (The "enable trigger happy triggers" button in the UI is also activated)

**Comment by tposney** [comment]
Can you send me the trigger happy journal entry? Then I can test what is
happening.

**Comment by YaruKo** [comment]
@Token[Lureg]@Trigger[click]@Macro[Lureg Greeting] (I hope you mean this)

The macro is set as "script"

**Comment by kakaroto** [comment]
> @token[Lureg]@trigger[click]@macro[Lureg Greeting] (I hope you mean this)
> 
> The macro is set as "script"

I think it should be `@Token[Lureg]@Trigger[click]@Macro[Lureg Greeting]` for it to work.

**Comment by tposney** [comment]
Beat me to it by seconds. Yes, Trigger Happy is case sensitive. Also, make sure there is no formatting inside the text - examine it with the <> option in the editor and it should look like
<p>@Token[Lureg]@Trigger[click]@Macro[Lureg Greeting]</p>

**Comment by YaruKo** [comment]
The @ caused it to look different I have it all in upper case sry :)

But it looks like I had a formatting error somewhere, I copied the Line from @kakaroto and suddenly it works. 

However when I write it exactly like that it doesn't work, only if I copy it (also the font looks different if i copy it)

**Comment by tposney** [comment]
It's almost certainly the formatting of the line (the font looking different is a clue). Select the line and choose Ix on the edit bar and also check the line via <> from the edit bar, which will show you the html that is actually stored for the text.

**Comment by YaruKo** [comment]
![Source code](https://user-images.githubusercontent.com/85389407/122664566-9040b900-d1a2-11eb-8496-6a3651c2413d.png)

Thats what it looks like in thhe html screen, pressing Ix to clear the formatting doesnt change anything :/
