### ISSUE TITLE
Macro to Delete or change token name once triggered?

### ISSUE THREAD

**Issue by Teech77** [League-of-Foundry-Developers/fvtt-module-trigger-happy#39]
I’m finding that clickable triggers get spammed by players. I can’t code, but is there a macro that would delete a trigger token once it’s been triggered? Better yet, a macro that could alter the name of the token (which would disarm it), and another macro to change it back.

**Comment by yoannfelix** [comment]
I just upgraded to Foundry VTT 0.8.8 and I was getting the same issue. It seems to be happening intermittently. When I reload Foundry some of them are there. I am really confused.

**Comment by tposney** [comment]
> I’m finding that clickable triggers get spammed by players. I can’t code, but is there a macro that would delete a trigger token once it’s been triggered? Better yet, a macro that could alter the name of the token (which would disarm it), and another macro to change it back.

Probably the easiest solution is to make the token hidden once it has been clicked - this means the player's cant click on it again. 
Here is the trigger happy line to run the macro:
```
@Token[Cat]@Trigger[click]@ChatMessage["the cat was poked"]@ChatMessage[/ToggleToken]
```
You need to create a script macro called ToggleToken and set it's execute as GM flag. Then  put this as the macro command
```js
await token.document.update({"hidden": !token.document.data.hidden})
```
You just right click and unhide the token to make it active again.

**Comment by tposney** [comment]
I don't understand what you mean by "I'm getting the same issue".  What do you mean by "some of them are there". Please provide some more info.
