### ISSUE TITLE
Unable to lock doors after using door trigger

### ISSUE THREAD

**Issue by Wombees** [League-of-Foundry-Developers/fvtt-module-trigger-happy#40]
Foundry v0.8.8
Trigger Happy v0.8.7

After using a trigger on opening/closing a door, that door is unable to be locked. Neither right clicking on the door nor manually editing the door works, the door stays in an unlocked state.

**Comment by Wombees** [comment]
Did some more testing with a fresh world and it seems to be a clash with AmbientDoors.

**Comment by tposney** [comment]
I tried with Ambient Doors installed as well and cannot repro the problem. Is it still present or did it resolve itself. If still present I'll need more info to try and see what is going on.

**Comment by Wombees** [comment]
My mistake - it's also an interaction with Advanced Macros. Essentially I'm using the door triggers to hide a tile via an advanced macros call.

Here's a trigger example:
`@Door[1900,1000,2100,1000] @Trigger[doorClose doorOpen] @ChatMessage[/doorhide vyn8DvVYfRVJMpYr]`

And here's the doorHide macro:
`let tilename = canvas.background.tiles.find(t => t.id === args[0]);
let v = !tilename.data.hidden;
tilename.document.update({hidden: v});`

**Comment by tposney** [comment]
I tried reproducing using you macro and a door. I can lock/unlock/open close the door. The only thing I can't do is lock the door when it is open, which I don't think is supposed to work.
