### ISSUE TITLE
Advice on debugging, as has just stopped working

### ISSUE THREAD

**Issue by retrodans** [League-of-Foundry-Developers/fvtt-module-trigger-happy#41]
I was tinkering with some landing pages, and the trigger happy actors no longer do anything on click, when they did before.  The module i installed (and then removed) was "Compendium Folders" although I am not sure that was the cause, just when I noticed it.  Is there any known things to look out for, or areas in the code with me adding some logging?

![actor](https://user-images.githubusercontent.com/259789/126555827-881c5f3f-6d4b-44ba-8b79-48f6587d5751.png)

![journal](https://user-images.githubusercontent.com/259789/126555829-6b96a14b-4663-4751-aea3-6b579e7640e3.png)

**Comment by retrodans** [comment]
Thanks for any time and/or advice you can give.

**Comment by tposney** [comment]
Apologies for not responding. The most common problem is the disable trigger happy button on the canvas. The smiley face in the attached screenshot. There is also a trigger happy setting to disable the button.

![Screenshot from 2021-05-18 23-49-39](https://user-images.githubusercontent.com/4486143/126933272-43e14c6b-9e76-4b67-9cbf-46d6986e2bad.jpg)

**Comment by retrodans** [comment]
So that is highlighted to show it is on as far as I can see sadly, so possibly something else.

![Screenshot from 2021-07-31 17-48-00](https://user-images.githubusercontent.com/259789/127746768-f17012fb-5010-4a76-ac5f-6fe77ee3b723.png)

It's very odd that it was working fine until "Compendium folders" was installed (and since been uninstalled).

**Comment by tposney** [comment]
Apologies for not getting back to you. The most likely issue is that that there are some non-printing html elements in the file that is causing trigger happy to fail to parse the file.

Try editing the trigger happy journal entry, select all the text and then click the Ix button and save the entry.

Failing that can you export your trigger happy journal to json and post it here and I'll have a look

**Comment by p4535992** [comment]
The error still persist on 0.8.21 ?
