### ISSUE TITLE
Updating to the same version

### ISSUE THREAD

**Issue by thatlonelybugbear** [League-of-Foundry-Developers/fvtt-module-trigger-happy#43]
Whenever I click on update or update all:
![image](https://user-images.githubusercontent.com/7237090/127855993-718a431c-5aa6-4a54-ba5c-fc4fdcfc9f95.png)
Uninstalled and installed again but the issue persists.

As a side note, also this. The version seems to have an incorrect format (0..8.6)
![image](https://user-images.githubusercontent.com/7237090/127856073-a8c55b04-fcca-4a03-a05c-8030a923d109.png)

**Comment by ericloyd** [comment]
Same issue, same details.  Code says it's 0.8.7 on the modules page (not the pop-up install page, but the general overview page).

**Comment by tposney** [comment]
Should be fixed now. Reopen if I'm wrong
