### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by cptnbananajam** [League-of-Foundry-Developers/fvtt-module-trigger-happy#45]
I had set up triggers with move capture and teleportation like it said online. I started with @Token and then changed it to @Actor. The change turned it into a clickable tab, but the rest didn't change. I tried the teleport function and it became two clickable tabs, but moving over the token didn't stop the token's movement or prompt anything. Originally for the trap it stopped the token and prompted them to make a perception check. The token actually stopped and a message came up in the chat window. Is there a difference now with all the updates? I thought it might be the icon that needed to be turned off and on again, but that didn't do anything. I even tried clicking the macro that was given to me. But it didn't do anything either.

So I am not sure if there are new things like changing the word Token to Actor helped, but @Trigger just stays as text. Are their new commands I am not aware about? Do I need to add more to the statement to get it to trigger properly?

**Comment by tposney** [comment]
Can you attach your trigger happy to the issue? It's hard for me to follow what's going on without the actual trigger happy text.

**Comment by cptnbananajam** [comment]
sure,

Traps

@Actor[Perceptioncheck]@Trigger[capture move]@ChatMessag[roll perception]

@Actor[Traps]@Trigger[capture move]@ChatMessage[/DoTrapAttack Traps "Fall80FT" Traps]



Teleportation

@Actor[Teleportation1]@Trigger[TeleportToToken]@Scene[TTI]

@Actor[Teleportation2]@Scene[TTI]

This is what I have so far. The first trap I set up with Perceptioncheck use to work. The only thing I Changed was @Token to @Actor. The first teleportation one I set up wasn't what you see there. It was:

@Token[Teleport1]@Trigger[capture move]@ChatMessage[/TeleportToToken Teleport2 0 0]

I also tried putting Teleport2 in "", but that didn't work either. I set up an actor with all the traps I wanted and gave each trap a different name. I tried the token as an npc and as a pc. I tried just putting the trap token down, and putting a transparent token that is set to represent the traps token I made. Neither worked.

**Comment by cptnbananajam** [comment]
That was a copy and paste, but in the original text @Trigger and @Scene is capitalized.

**Comment by tposney** [comment]
Can you try making the @fields upper case?

**Comment by cptnbananajam** [comment]
It won't let me here, but in the actual journal in foundry-vtt on the forge-vtt has capital letters. Trigger, Scene, Actor, Token, are all written capital in the journal entries.

**Comment by tposney** [comment]
Yes, I realised - that's why I changed the comment if you enclose the line in triple tic marks it will honor the upper case.
The revised reply explains what is wrong with the entries you have.

**Comment by cptnbananajam** [comment]
So I think I may have messed the macro up some how. Should I uninstall and reinstall the asset?

And basically what I want them to do is:
Traps when walked on stops player and prompts them to make a save. The save is made by the player and the trap deal damage to the player. 

Teleport a player to a new scene you said needs to have a copy of the actor on the new scene, right? Then it should just load the scene for the player?

**Comment by cptnbananajam** [comment]
So ideally it's a pit trap. When the player steps on Actor Traps I want them to fall down an 80 ft. chasm. I named the other Actor Trap Effects.

@Actor[Traps]@Trigger[capture move]@ChatMessage[/DoTrapAttack TrapEffects "Fall80FT" Traps]

While the capture effect is now in place, it isn't triggering the /DoTrapAttack macro.

**Comment by tposney** [comment]
Can you try the Fall80FT not in quotes? I think it will be calling DoTrapEffect with the argument enclosed in quotes which means I don't think it will find the itemto attack with. And just to confirm you have a world actor called TrapEffects?

**Comment by cptnbananajam** [comment]
Yes I have the actor called Trapeffect with all of the traps. I have tried both with quotes and without quotes. I'm not sure how I did it, but one time it triggered for a dex roll, but no damage. Then it wouldn't trigger again.
