### ISSUE TITLE
Triggers work for GM only?

### ISSUE THREAD

**Issue by Heljspe** [League-of-Foundry-Developers/fvtt-module-trigger-happy#46]
Triggers are working for the GM, but not the players. 
The exception is actor>actor triggers, so both the below codes work: 
@Actor[IDMygJK7xUz9oGNm]{Party Chest}@Actor[IDMygJK7xUz9oGNm]{Party Chest}  
@Actor[Gp5srV3PjdrGsAut]{BlackIron Blades Shop}@Actor[Gp5srV3PjdrGsAut]{BlackIron Blades Shop} 

But these ones do not work (for players, works for GM): 
@Actor[KcOCnfjFLe5Nwumv]{16}@JournalEntry[svM5rT5KZgCsPVJR]{Session 016 - The white moose of Lonelywood}
@Actor[TSJFh43P2voZHlxY]{Quest Log}@Macro[uN4luEV4rC4Mw4nW]{Questing}
@Actor[3wtmKQhVWGcwA1Hl]{Icewindale}@Scene[NWU0ZDZmZTBiODY0]{Icewind Dale}
@Actor[TAmWFLXiXjtbxjFK]{Fire}@Trigger[click]@RollTable[NQQXB1SaoKf3ESzX]{Flame}

All were working 2 weeks ago. Codes created by dropping and dragging actor then journal entry (or scene, etc). 

No errors in console (console does nothing when player clicks trigger).

**Comment by tposney** [comment]
That all looks ok to me.

Can you make sure that the links are still correct - i.e. the trigger happy journal should have valid links displayed?
file:///home/timp/Pictures/Screenshot%20from%202021-08-19%2013-20-11.jpg

I am assuming that you've confirmed that the users have permission for the entities being referenced as the targets.

Can you attack your entire trigger happy journal for me?

**Comment by thul** [comment]
@tposney 
I can confirm this. This is my trigger happy journal
```
@Token[Party]@JournalEntry[mcN3qKN1uoPv3Tfe]{The Party}

@Token[Patron]@JournalEntry[E64VjpFLiTiTLDKr]{Inquisitor Tytrona Dikaisune}

@Token[The Mission]@Macro[aFWmvN936Fd28VIK]{Quest Log render}
```
GM user can click and it works. Regular use can click but nothing is fired.

Trigger Happy Version: **0.8.8,** 
Foundry VTT version: **0.8.7**

**Comment by thul** [comment]
Any news about this? I tried making a new user to test, they were able to use triggers... but all my existing players can't. Only GM can

**Comment by Heljspe** [comment]
Sorry for the delayed reply, work got hectic. 
Figured out a workaround, but that doesn't really help: the triggers only seem to work if the party members are owners of the token they're clicking on (observer doesn't work).  
The problem then though is that I have a bunch of transparent tokens over tiles, so when they click an image, it does the thing. If they have to own the token, they might move it, or delete it. It also adds a bunch of transparent party members to monks token bar thingy (which is annoying :p). Even if I replace the transparent tokens with the tile image, its still a bunch of player characters that are just supposed to be links.  
![image](https://user-images.githubusercontent.com/68180128/133567784-2dc0acb8-ab27-4947-b428-56175ed77d25.png)

Before, it used to let me use the tokens without the players having any rights to them (and thus they didn't show up on the token bar either). But that would explain why the GM could click (because they own all the tokens) but the players couldn't.

**Comment by tposney** [comment]
I've had a couple of reports of this. There is no requirement for players to own tokens for trigger happy to work.

Assuming the triggers all work fine for the GM, then the problem seems to be that something is stopping the mouse event from firing for players. I am guessing some module interaction, but don't really know which. Can you try with just trigger happy enabled and see if player interactions work? Just to see if that is the issue.

**Comment by tposney** [comment]
> Any news about this? I tried making a new user to test, they were able to use triggers... but all my existing players can't. Only GM can

I think there is a module interaction that is stopping the mouse events from getting passed to trigger happy. Can you try with other modules disabled and send me a list of the other modules you have active,

**Comment by tposney** [comment]
I can take no credit, but pleased it is working again.
