### ISSUE TITLE
I fixed it, but I have follow questions

### ISSUE THREAD

**Issue by cptnbananajam** [League-of-Foundry-Developers/fvtt-module-trigger-happy#48]
![Triggers](https://user-images.githubusercontent.com/83311393/131259089-8b837bd9-13d6-44fb-b6d4-05c8fe5559ec.png)

I rewrote the line like this, and it captures and triggers. It also repeats the trigger whenever walked on. Is there a quick way to turn off the trigger if the trap should only trigger once?

![Half Damage](https://user-images.githubusercontent.com/83311393/131259181-91bc00b1-58ce-41ef-a566-1be3e2a3dd9b.png)
![TrapEffect](https://user-images.githubusercontent.com/83311393/131259257-f192e1bd-4127-4e22-89bd-a09585da94a0.png)

I have the details setup this way, with half damage on save. However it doesn't give me half the damage as a result, nor does it apply damage to the token. Is there a way to fix the half damage? Is here a way to have it automatically assign damage to a token?

**Comment by tposney** [comment]
The damage roll is correct, it rolls the normal damage and if you are using midi-qol it applies half damage on save. Are you using midi-qol?
