### ISSUE TITLE
Feature Request: @Compendium Triggers

### ISSUE THREAD

**Issue by TheGreatRedDuke** [League-of-Foundry-Developers/fvtt-module-trigger-happy#50]
Hi, I love this module, but I'm running into a little problem while trying to use it for my worlds.

I have a lot of data packaged up in a compendium module and I'm using the [Scene Packer](https://github.com/League-of-Foundry-Developers/scene-packer) module to bundle it all up. As part of this process, I'm using the "Relink compendium journal entries" macro that comes with it to ensure that my collection of journals always work when imported into a new world.

This would convert my journal entry text from something like:
 
 `@Drawing[nav-absalomStation]@Trigger[click]@Scene[nU93caH4Nj2hZH2y]{Absalom Overview}`
to 
`@Drawing[nav-absalomStation]@Trigger[click]@Compendium[my-shared-module.scenes.tT4T0WQqyA93RIlc]{Absalom Overview}`

But once this is done, my Trigger Happy setup no longer functions because there's no @Compendium trigger. I think my only choice then it to manually recreate all my triggers after importing my module data into the world, which is a ton of work and is kinda a bummer since I'm trying to abstract all my shared data nicely. It would be awesome if Trigger Happy could work for @Compendium triggers.

I'm not sure how much effort this feature would be to create, but it would be a very welcome addition to this already amazing module.

I'm happy to provide any other info that could be helpful.

**Comment by tposney** [comment]
That makes sense - I will have a look into it.

**Comment by tposney** [comment]
Will go out in 0.8.10
