### ISSUE TITLE
Feature request - Add support for new Forien Quest Log 0.7.7 link for "trigger" the quest journal

### ISSUE THREAD

**Issue by p4535992** [League-of-Foundry-Developers/fvtt-module-trigger-happy#52]
With the new version of Forien Quest Log 0.7.7, we can now copy the id of the quest log and "trigger" like a journal or a scene.

Here the video on the exact minute:
https://youtu.be/lfSYJXVQAcE?t=586

So we can connect a tile with a Quest or a token with a quest, ecc.

**Comment by tposney** [comment]
I just tried this and @Quest links seem to work fine. If there are any problems please reopen
