### ISSUE TITLE
@Token is an unknown Tag?

### ISSUE THREAD

**Issue by MrDoctorJunior2** [League-of-Foundry-Developers/fvtt-module-trigger-happy#53]
I am unsure as to why, but trying to refer to Tokens brings up:
`Unknown Tag "Token"`

I don't have any modules that would change tags except for possibly Obsidian Character Sheets, but I am trying to refer to a Default Foundry Token.

**Comment by p4535992** [comment]
Disable all the module except trigger happy and check if the error persist

**Comment by MrDoctorJunior2** [comment]
Oddly the error still occurs... but the module now works fine? Unsure as to why that is bu I'll close this for now.
