### ISSUE TITLE
Installation failed: Not found

### ISSUE THREAD

**Issue by Psyko90** [League-of-Foundry-Developers/fvtt-module-trigger-happy#55]
I can't install Trigger Happy if i try it i get the message Installation failed: Not found in a red bar

![Failure](https://user-images.githubusercontent.com/13080313/134338978-394a48f4-073b-4593-ba13-2012ccc6922c.png)

**Comment by professorx00** [comment]
module.json has a 404 for the package listed

**Comment by tposney** [comment]
Apologies, should be fixed
