### ISSUE TITLE
Package trigger-happy is using the old "systems"

### ISSUE THREAD

**Issue by mummson** [League-of-Foundry-Developers/fvtt-module-trigger-happy#56]
Is this warning an "issue"? I have tried to uninstall and install again but alway's get this when I press "update all" in the FVTT config.
`[warn] Package trigger-happy is using the old "systems" manifest key where a "system" key is expected`

**Comment by tposney** [comment]
It's not an issue, just reflects laziness on the part of the author.

**Comment by mummson** [comment]
> It's not an issue, just reflects laziness on the part of the author.

I can relate to that...

**Comment by krobibero** [comment]
It would be really nice to see this get fixed.  When updating modules, my console fills up with this error over and over.  Kinda annoying.  :-S

**Comment by tposney** [comment]
Should be fixed in 0.8.11
