### ISSUE TITLE
Actor type

### ISSUE THREAD

**Issue by jasharen** [League-of-Foundry-Developers/fvtt-module-trigger-happy#57]
Is it possible to have a custom actor type for trigger happy tokens? This would help avoid interaction with normal frameworks.

For example, in Fate Core Official, the fate utilities show all tokens in a scene on the battle tracker. Including TH tokens because they are still essentially Fate Core tokens with full character sheets.

Thanks!

**Comment by tposney** [comment]
Sorry for taking so long to get back to you on this. I've been trying to see if there is a simple way to implement this without breaking all the existing usages and could not come up with anything.

But I'll keep thinking about it.

**Comment by p4535992** [comment]
On my [PR #58](https://github.com/League-of-Foundry-Developers/fvtt-module-trigger-happy/pull/58) i add a tagger feature integration so you can filter not only for the actor type but with a combination of tags on any placeables object.
