### ISSUE TITLE
[Bug] Enable Trigger Happy triggers "button" not working 100%

### ISSUE THREAD

**Issue by Mavendorn** [League-of-Foundry-Developers/fvtt-module-trigger-happy#59]
The quick change button to enable/disable trigger happy triggers does not fire the onChange callback until hooked by opening the settings menu or creating/deleting a journal. trigger happy continues to have the same enableTriggers state setting until a hook is called.  this bug was introduced in v0.8.9

tested with only trigger happy installed.

**Comment by tposney** [comment]
Thanks for the heads up. It was the result of a merge that I did not adequately review.

**Comment by Mavendorn** [comment]
Thanks for the quick update, as an additional note, the button seems to only disable the triggers for the GM. players can continue to trigger events in the journal even with triggers disabled. (testing with older versions also shows this is how its always been) is this intended?
