### ISSUE TITLE
make compatible with levels

### ISSUE THREAD

**Issue by rinnocenti** [League-of-Foundry-Developers/fvtt-module-trigger-happy#61]
Some things are not 100% compatible.
for example, when the targets are all those on the tile, the module does not recognize the height of the tokens and takes all those in the 2d area of the tile.

Another incompatibility is showing/hiding the tile.
If it has a level, display the tile will always change its position (if it's a floor tile, when it is displayed it changes to a level tile getting on top of the token.

**Comment by tposney** [comment]
You are right it is not compatible with levels - trigger happy has not concept of token/tile height.

I'll look at adding levels compatibility, but I suspect it is not so simple as it requires significant binding to the levels module to make it work and I'm not 100% certain that it's a good idea. But I will look

I don't think I understand the second problem. Could you give me an example I can try? How are you making the tile visible?

**Comment by rinnocenti** [comment]
So sorry I put this in wrong project.. should be the monkey module
