### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by cptnbananajam** [League-of-Foundry-Developers/fvtt-module-trigger-happy#65]
I updated Trigger Happy today, November 30th, 2021. I made sure I updated all assets a few times to make sure I am up to date. I have had triggers set from before the update, and they worked. Now they do not trigger at all. 
![Triggers](https://user-images.githubusercontent.com/83311393/144152500-22a8b8e7-e4d7-45dd-a1e7-3875b9c787d3.PNG)

These are the triggers I have set up. The teleportation ones aren't working, but that is another story. The trap ones I have setup are the ones i am most concerned with. They worked before, they would capture the player token and bring them to the center and would either whisper into the chat, give an overall message, or trigger the appropriate rolls. None of that works now. Have I messed something up in updating, or missed some important information about a change?

**Comment by tposney** [comment]
The recent version change seems to have introduced a bug where `@Trigger[capture move]` does not work, but `@Trigger[capture]@Trigger[move]` does work.

I'll have a look at whats going on, but in the interim you can make that change to your trigger happy journal.

**Comment by Rubengam3r** [comment]
I am seeing this issue as well. But as it looks like you are already on it I will not duplicate it.

**Comment by cptnbananajam** [comment]
Just curious, did it also create a bug where @whisper doesn't trigger? Changing it to @Trigger[capture] and @Trigger[move] worked, but I noticed the @whisper doesn't work now.

**Comment by tposney** [comment]
The @Trigger[capture move] should be fixed in the latest release.
The format for the @whisper in your example is not the one that is currently supported. (I'm not sure if it changed in the most recent releases).
Anyway the format that works is 
```
@Token[SlipAndFall]@Trigger[capture move ooc whisper]@ChatMessage[Roll a dexterity saving throw]
```
I noticed that ooc overrides whisper so I'll put in a fix for that.
