### ISSUE TITLE
Doors Won't Trigger

### ISSUE THREAD

**Issue by 13jtibbitts** [League-of-Foundry-Developers/fvtt-module-trigger-happy#68]
It appears that after the recent update to **0.8.16**, I can't seem to trigger any `@Door` I have in my Trigger journal.
Here is a screenshot of the relevant triggers. The **0.8.17** update didn't appear to fix this either.
![image](https://user-images.githubusercontent.com/45647359/144375562-bf5cf617-406a-4c8a-aac4-baba18e4f611.png)

Looking at the console, I get the warning for each door:
> `trigger-happy |  Can't manage the config with entity 'door' and key 'undefined' on '@Door[each door coords]`

I have inserted console.log into the macro it triggers with Advanced Macros just to test if it appears, and it does not, so it appears the `@Door` trigger isn't working for me.

**Comment by p4535992** [comment]
On my test door seem to work, i will investigate it anyway, but maybe you can try the new configuration 

`@Door[*]@Tag[human readable label]`

where the label of the `@Tag` is the list of tag you put with the Tagger module on the placeable object.
so you can move the door without retouch the coordinates .

**Comment by p4535992** [comment]
K should be fixed in 0.8.20
