### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Verodox** [League-of-Foundry-Developers/fvtt-module-trigger-happy#74]
**Module Version:** v0.8.21

**Describe the bug**
The @Trigger[click] doesn't work for some reason

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser:**
![Trigger Happy error](https://user-images.githubusercontent.com/96009261/145714007-87387040-cb16-4ecc-af42-48a94cfacc62.png)

 - 

**Foundry Version:** 
0.8.9

**Game System:** 
Dnd5e

**Additional context**
I've installed Trigger Happy and NPC Chat and I'm trying to replicate what this video (https://www.youtube.com/watch?v=W6z0pMUBAz8) did.

**Comment by p4535992** [comment]
Have you activated the module 'NPC Chatter' ?

I try that tutorial and it' seem to work to me.

Here the trigger i put on the journal:

`@Token[Catharina Combat]@Trigger[Click]@Macro[eD2rpXMTXTuo7Bh2]{Catharina Merchant Chatter}`

and here the macro with name 'Catharina Merchant Chatter' (you can do a better macro it' just a example):

```
var NAME = "Catharina Combat";
var token = game.scenes.filter(x => x.active)[0].data.tokens.filter(x => {
// console.error(x.name);
if(x.name.toLowerCase().includes(NAME.toLowerCase().trim())){
  return x;
}
})[0];
// console.log(token.name);
game.npcChatter.tokenChatter(token);
```
