### ISSUE TITLE
 Can't manage the config collection with entity 'drawing' and key 'Drawing' on '@Drawing[NAME]'

### ISSUE THREAD

**Issue by kiligir** [League-of-Foundry-Developers/fvtt-module-trigger-happy#75]
**Module Version:** v0.8.21

**Describe the bug**
So I have an issue with Trigger Happy where it just spams Can't manage the config collection with entity 'drawing' and key 'Drawing' on '@Drawing[NAME]' to my console for every drawing I've used repeatedly until the browser seizes up, likely due to a memory leak. The NAME cycles between several different drawings. Is there a fix for this? What's it even saying?

I'm on Firefox, but this happens in Chrome as well. I'm running DnD 5e 1.5.5 with Foundry Version 0.8.9.

**Comment by p4535992** [comment]
That message ''Can't manage the config collection with entity 'drawing' and key 'Drawing'" usually mean the trigger you are try to "get" (in this case a drawing) is not on the current scene/canvas. For example on the load of the scene A i have a drawing with the label 'Arena' then with this text i load a trigger.

`@drawing[Arena]@trigger[click]@scene[go to scene b]`

when i click on the drawing it's go to scene B, During the loading of the scene B i got the  warning 

`Can't manage the config collection with entity 'drawing' and key 'Drawing' on '@drawing[Arena]'`

and it should be fine,  it just a warning for let you know on this scene it was no possible to load that trigger.
For avoid the warning i have preparared these two additional setting :

- Enable 'journal for every scene' integration feature
- Enable 'only use journal for every scene' integration feature

they should help to make the warnings disappear and avoid to parse all the journals under the 'trigger happy' folder, the fact that it goes in a loop it's strange, can you pass the text of the journal you are using?

**Comment by kiligir** [comment]
Sure! The full text is below:

```
@Drawing[AltaButton]@Macro[HMkJahg73kKmqVfR]{Menu Sound}@Actor[pvZhijbfd6NpzDqR]{Alta Meior}

@Drawing[AsteriaButton]@Macro[HMkJahg73kKmqVfR]{Menu Sound}@Actor[rTk8jrjaQY1Cjv5U]{Asteria}

@Drawing[CeresButton]@Macro[HMkJahg73kKmqVfR]{Menu Sound}@Actor[B9ReidEgMkWf3MdZ]{Ceres Duskfire}

@Drawing[LianthusButton]@Macro[HMkJahg73kKmqVfR]{Menu Sound}@Actor[JtQ3B7NWJrldVmh3]{Professor Lianthus Alu'thar}

@Drawing[SylasButton]@Macro[HMkJahg73kKmqVfR]{Menu Sound}@Actor[fgq1IkMZwmkghwON]{Sylas Graves}


@Drawing[AurorasLogs]@Macro[HMkJahg73kKmqVfR]{Menu Sound}@JournalEntry[CtJTBjiXJ6ZRUrvN]{[00] Aurora's Logs - Master Index}

@Drawing[Calendar]@Macro[HMkJahg73kKmqVfR]{Menu Sound}@Macro[KOpOea9tbsTbhHzS]{Open Calendar}

@Drawing[Constellations]@Macro[HMkJahg73kKmqVfR]{Menu Sound}@Scene[MMyFJA3lZ9FFaN6O]{Ascended Constellations}

@Drawing[QuestLog]@Macro[HMkJahg73kKmqVfR]{Menu Sound}@Macro[nuyw9LY1PqFuyrX5]{Open Quest Log}


@Drawing[Return]@Macro[HMkJahg73kKmqVfR]{Menu Sound}@Scene[n8aNizf2vYdHYIwv]{Splash Screen}

@Drawing[ConstInfo]@Macro[HMkJahg73kKmqVfR]{Menu Sound}@JournalEntry[LMWkBVddsx0ZGLBB]{Constellation Information}
```

**Comment by p4535992** [comment]
@kiligir the issue still persist with the last version of the module ?

**Comment by kiligir** [comment]
It isn't persisting, apologies! I forgot to close this.
