### ISSUE TITLE
Allow modules and macros to add custom trigger effects

### ISSUE THREAD

**Issue by CDeenen** [League-of-Foundry-Developers/fvtt-module-trigger-happy#76]
In Shared Vision I used a method to toggle vision sharing through Trigger Happy. Unfortunately this no longer works, as it appears that Trigger Happy no longer allows custom trigger effects (I don't know when this was changed, but the method I used was a workaround, so it doesn't surprise me that much).

I'd like to propose the following feature:
Modules and macros can register a custom effect, either through some function, or a hook. For example: `game.triggers.registerEffect('SharedVision')`
This allows the following effect to be added: `@SharedVision[data here]`. For example, in a full Trigger Happy line, it could be `@Token[tokenName] @Trigger[move] @SharedVision[enable]`.
In this case, whenever the token is moved, a hook is called that passes the effect and data: `Hooks.call('TriggerHappy','SharedVision','enable')`

**Comment by p4535992** [comment]
yea i like the idea not sure why it should stop to work, there it was a big update between 0.8.11 and 0.8.14 maybe i broke something.... I put in copy @tposney if he would like to expose some ideas about it .

**Comment by p4535992** [comment]
Here the beta: 

`https://github.com/p4535992/fvtt-module-trigger-happy/releases/download/v0.8.23/module.json`

detail on the readme let me know.

**Comment by CDeenen** [comment]
That works great, thanks!
I do get the following warning in the console: 
`Can't manage the config with entity 'sharedvision' and key 'undefined' on '@sharedvision[toggle]'`

**Comment by p4535992** [comment]
A because some hook is on the init phase... I'll try to avoid that. I'll let you know.

**Comment by p4535992** [comment]
Here we go a updated beta let me know if you still see the the warning (or if i broke something):

`https://github.com/p4535992/fvtt-module-trigger-happy/releases/download/v0.8.24/module.json`

**Comment by p4535992** [comment]
@CDeenen sorry to bother. Have you find the time to test the version 0.8.24 ? if everything is ok i will merge the on the official project.

**Comment by CDeenen** [comment]
Sorry for not getting back at you earlier, I've been busy due to the holidays.
It's working great in the above v0.8.24 beta.
