### ISSUE TITLE
Add custom html rendering for the TinyMCE editor

### ISSUE THREAD

**Issue by Turreaux** [League-of-Foundry-Developers/fvtt-module-trigger-happy#77]
Everytime I try to create a trigger using the @ I get an error saying unknown tag. I have turned tagger off and on, the line for enable tagger is blank. Please help.

**Comment by Turreaux** [comment]
If I drag and drop the actor to the journal it will load just fine, but if I try to key in a specific token. It doesn't recognize that.

**Comment by p4535992** [comment]
Can you share your text journal ? 
Can copy and paste  (or made a screenshot) of the error ? 
What version of Foundry are you using ?
What browser are you using ?

**Comment by Turreaux** [comment]
![image](https://user-images.githubusercontent.com/96503734/147104542-f1a3412d-84ef-4c80-b11e-47fda979071b.png)
![image](https://user-images.githubusercontent.com/96503734/147104595-c2239d5f-fd7f-4e4b-ba5a-2493eca60ff5.png)
![image](https://user-images.githubusercontent.com/96503734/147104980-c9b0ef14-6cf0-4160-b6da-2a0cd3ab19bd.png)
![image](https://user-images.githubusercontent.com/96503734/147105249-c80b054f-df7e-4105-8ca3-7c34d6b5c094.png)
Foundry Version 0.8.9
Browser: Chrome 96.0.4664.110

**Comment by p4535992** [comment]
a ok sorry I misunderstood your doubt, the word "tag" made me think of the integration with the "Tagger" module. Yes Tinymce does not render the keywords used by the default module such as @Trigger[XXX] or @TOKEN[YYYY].

As soon as I find some time I wanted to do as for the "Sound Link" module and add the custom rendering, but it's not a real mistake your macro should still work anyway.

**Comment by Turreaux** [comment]
The triggers still do not work. If I drag the actor into the journal it
will accept that as valid but still gives the error on the @trigger[click]
and does not work when I click on the token. My guess is because I am
referencing the Actor and not the Token but I can't figure out how to drag
the individual token into the journal entry since typing it in does not
work.

**Comment by p4535992** [comment]
is work with @Actor, but on the canavs/scenemust be present a token be linked to that actor, make sure the checkbox "Linkded to daùta" is check on the token configuration.
Just for be sure pass me the text of your journal  i will test and give you confirmation

**Comment by Turreaux** [comment]
Here is the journal text:
@Actor[m0DkIJTnaEHJ0fyy]{OGB} @Trigger[Click]
@Folder[A8JURtYEbxkZnodD]{Into the Wilds Forest}

Both token and actor are named OGB with the Link Actor Data box checked.

I have screenshots from a previous attempt that was giving the same issue
at this link:
https://www.reddit.com/r/FoundryVTT/comments/quihqw/trigger_happy_trigger_not_working/
<https://www.reddit.com/r/FoundryVTT/comments/quihqw/trigger_happy_trigger_not_working/>

Foundry version 0.8.9 using system DnD5e 1.5.6

**Comment by p4535992** [comment]
Can I ask you if you have read the README of the project? or if something in the documentation confuses you?

as for the screenshots of the reddit I highlight this:
 
The macro screenshot doesn't make any sense I don't know where you got the idea ... the module only ever worked with journalentry in the journals sidebar.

The @Item does not exist as a 'trigger', but only as an 'effect' so placing it as the first element of the line makes no sense. Look at the READEME table  where I highlight all the valid triggres.

Finally I confirm that the line of code you passed is correct, my example works perfectly I report it to you below for confrontation:

`@Actor[es5E8fb1jso36zbH]{Guard}@Trigger[click]@Folder[ejReto73e8wCeehk]{CM - DnD5 Cheatsheet}`

the module is case insestive for the key elements so the following line work either:

`@Actor[es5E8fb1jso36zbH]{Guard}@trigger[click]@folder[ejReto73e8wCeehk]{CM - DnD5 Cheatsheet}`

Make sure the trigger happy button (the one on the left see image on the README) is active.

and I'm sorry in the previous comment I said something wrong, to make the trigger work with the @Actor annotation **YOU DON'T NEED TO SET THE 'Link Actor Data' only the 'Represented Actor' parameter**, like in the image i pass to you before.

Cheers.
