### ISSUE TITLE
[BUG] Unknown Tag problem

### ISSUE THREAD

**Issue by Ermine09** [League-of-Foundry-Developers/fvtt-module-trigger-happy#79]
**Module Version:** v0.8.25

**Describe the bug**

I am not able to set teleportation tokens. I set everything according to the instructions, but trigger happy doesn't seem to recognize tags so tokens are not working as teleports - I'm sending few screenshots.

![TH1](https://user-images.githubusercontent.com/96796028/147605777-6d5d3b5e-42cf-4fc8-b4c7-3b0b84ec1f8c.png)

![TH2](https://user-images.githubusercontent.com/96796028/147605786-357355cf-a3c2-48c4-94cb-a085addd911f.png)
![TH3](https://user-images.githubusercontent.com/96796028/147605827-86000294-d46b-4779-933b-9dfc11121599.png)

**Foundry Version:** 
Version 9 - Build 238

**Game System:** 
DnD5e 1.5.6

What to do with this? Could it be problem with some incompatibility with other modules? I am sending srceenschots with my other modules. 

 
![Modules 1](https://user-images.githubusercontent.com/96796028/147605922-0920a052-0b49-4390-bada-09cf83c0e9ff.png)
![Modules 2](https://user-images.githubusercontent.com/96796028/147605928-90f75cb0-afaa-426a-8229-4d244652a739.png)

Thank you for answer, Dan

**Comment by p4535992** [comment]
related to https://github.com/League-of-Foundry-Developers/fvtt-module-trigger-happy/issues/77 Tinymce does not render the keywords used by the default module such as @trigger[XXX] or @token[YYYY].
On version 0.8.29 there is a new module settings 'Enable rendering of trigger with html on journal' for rendering this , is still in beta so i suggest to wait for the next release, but if you wanna try and encounter any problem you can just disabled it.
Remember it should be just a render html thing of the editor, you triggers seem fine to me.
As always any feedback or suggestion is wecome.
