### ISSUE TITLE
When Trigger Happy is activated, the Convenient Effect icon disappears (but the button is still there).

### ISSUE THREAD

**Issue by Padhiver** [League-of-Foundry-Developers/fvtt-module-trigger-happy#83]
When Trigger Happy is activated, the Convenient Effect icon disappears (but the button is still there).

I tested with Find the Culsprite and the icon comes back once Trigger Happy is desactivated.

![image](https://user-images.githubusercontent.com/80126915/147920757-339587d8-2026-48a1-96e9-01c38393824f.png)

(I dont know if im alone with that or not .. :o)
Thank you for all your work !

**Comment by p4535992** [comment]
ty for this i will fix very soon

**Comment by p4535992** [comment]
should be fixed with version 0.8.30 let me know

**Comment by Padhiver** [comment]
> should be fixed with version 0.8.30 let me know

It's fixed, thank you ! :D
