### ISSUE TITLE
Hide the Actor did not work as before System Update[BUG]

### ISSUE THREAD

**Issue by TheStoryTheDarkEye** [League-of-Foundry-Developers/fvtt-module-trigger-happy#84]
**Module Version:** v0.8.30

**Describe the bug**
Before the Foundry 9.0 System Update i used the function to hide the actor for the players, so the cant use the Trigger. Hide Actor = canot use Trigger / Unhide Actor = can use Trigger. Since the System Update the Player can use the Trigger doesnt matter it is hide or not. 

Im Not sure thats a bug or just a chance, but i would love when it get back to the "Hide = cannot use Trigger" State :P 

**To Reproduce**
1. Create a 'Trigger Actor'
2. Click on 'Switch visible Mode' (to invisible Mode) Button of 'Trigger Actor'
3. Click on 'Trigger Actor' 
4. Trigger will trigger (that's the 'Error')

**Expected behavior**
Trigger will not Trigger (like it was before)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/97088693/148031400-de0a73b3-9b70-4739-9745-20a6827c5258.png)

**Browser:**
Mozilla Firefox

**Foundry Version:** 
9.0

**Game System:** 
Das Schwarze Auge 5th Edition

**Additional context**
Add any other context (like other modules installed) about the problem here.

THANK YOU :) It's such a wonderful & great Module! ^-^

**Comment by p4535992** [comment]
I don't know exactly what you mean, I don't think the module has ever worked that way. But the module takes into account the permissions, so maybe you managed the permissions in such a way that the hidden elements were managed only by the gm?
However it was a simple thing and I added a module setting for your use case. I also added two new options `onlyIfHidden` and` onlyIfUnHidden` so you can specify at the single line trigger whether to fire only when it is hidden or not. The details can be found in the readme.
Try out version 0.8.31 and let me know .

**Comment by TheStoryTheDarkEye** [comment]
Hey p4535992,

i didnt know why it worked like the discribes way in my case before. But you change solved my Problem, so really thank you :)! 

I really love Trigger Happy, coud not image to use Foundry without it, so thank you so much for the work!

All the best for 2022 for you! ;)

Best wishes,

The Story
